import sqlalchemy as sa
from paginate_sqlalchemy import SqlalchemyOrmPage  # <- provides pagination

from ..models.blog_record import BlogRecord


class BlogRecordService(object):

    @classmethod
    def all(cls, request):
        query = request.dbsession.query(BlogRecord)
        return query.order_by(sa.desc(BlogRecord.created))

    @classmethod
    def by_id(cls, _id, request):
        query = request.dbsession.query(BlogRecord)
        return query.get(_id)

    @classmethod
    def get_paginator(cls, request, page=1):
        query = request.dbsession.query(BlogRecord)
        query = query.order_by(sa.desc(BlogRecord.created))
        query_params = request.GET.mixed()

        def url_maker(link_page):
            # replace page param with values generated by paginator
            query_params['page'] = link_page
            return request.current_route_url(_query=query_params)

        return SqlalchemyOrmPage(query, page, items_per_page=5,
                                 url_maker=url_maker)

    @classmethod
    def allow_editing(cls, request):
        user = request.user
        entry_id = request.params.get('id') or request.matchdict.get('id')
        allowed = False
        if user and entry_id:
            model = BlogRecord
            exists = request.dbsession.query(model).exists()
            match_entry = exists.where(model.id == entry_id)
            full_query = match_entry.where(model.author == user)
            allowed = request.dbsession.query(full_query).scalar()
        return allowed
